# Generated by Django 5.2.3 on 2025-06-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': '收入', 'verbose_name_plural': '收入記錄'},
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
